# Generated by Django 3.2.4 on 2021-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('endereco_ip', models.CharField(max_length=100)),
                ('filial', models.CharField(max_length=3)),
                ('tipo_estacao', models.CharField(choices=[('servidor', 'Servidor'), ('pdv', 'PDV'), ('farmaceutica', 'Farmaceutica')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
