# Generated by Django 3.2.4 on 2021-06-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroEstacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparacao', models.CharField(blank=True, choices=[('', '---'), ('and', 'AND'), ('or', 'OR')], max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('contains', 'Contem'), ('regex', 'Regex'), ('equals', 'Igual')], max_length=100)),
                ('campo', models.CharField(choices=[('hostname', 'Hostname'), ('endereco_ip', 'Endereço IP'), ('filial', 'Filial'), ('tipo_estacao', 'Tipo de Estação')], max_length=100)),
                ('valor_pesquisa', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='estacoes',
            options={'verbose_name': 'Estação', 'verbose_name_plural': 'Estações'},
        ),
        migrations.CreateModel(
            name='GrupoEstacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('filtros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.filtroestacoes')),
            ],
        ),
    ]
