# Generated by Django 3.2.4 on 2021-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210624_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestacoes',
            name='filtros',
        ),
        migrations.AddField(
            model_name='grupoestacoes',
            name='filtros',
            field=models.ManyToManyField(to='inventario.FiltroEstacoes'),
        ),
    ]
