# Generated by Django 3.2.4 on 2021-06-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210624_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestacoes',
            name='filtros',
        ),
        migrations.AddField(
            model_name='grupoestacoes',
            name='filtros',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.filtroestacoes'),
            preserve_default=False,
        ),
    ]
