# Generated by Django 3.2.4 on 2021-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20210624_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestacoes',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
