# Generated by Django 3.2.4 on 2021-06-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20210624_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestacoes',
            name='total',
        ),
        migrations.AddField(
            model_name='totalgrupoestacoes',
            name='grupo_estacoes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.grupoestacoes'),
            preserve_default=False,
        ),
    ]
