# Generated by Django 3.2.4 on 2021-06-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_filtroestacoes_comparacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtroestacoes',
            name='tipo',
        ),
    ]
