# Generated by Django 3.2.4 on 2021-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_estacoes_tipo_estacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestacoes',
            name='total_estacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TotalGrupoEstacoes',
        ),
    ]
