# Generated by Django 3.2.4 on 2021-06-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_grupoestacoes_total_estacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoestacoes',
            options={'verbose_name': 'Grupos Estações', 'verbose_name_plural': 'Grupos estações'},
        ),
    ]
