# Generated by Django 3.2.4 on 2021-06-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20210630_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacoes',
            name='tipo_pdv',
            field=models.CharField(blank=True, choices=[('omni_caixa', 'omni_caixa'), ('omni_balcao', 'omni_balcao'), ('pharmax', 'pharmax')], max_length=50, null=True),
        ),
    ]
