# Generated by Django 3.2.4 on 2021-06-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_estacoes_tipo_pdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtroestacoes',
            name='campo',
            field=models.CharField(choices=[('hostname', 'Hostname'), ('endereco_ip', 'Endereço IP'), ('filial', 'Filial'), ('tipo_estacao', 'Tipo de Estação'), ('tipo_pdv', 'Tipo de PDV')], max_length=100),
        ),
        migrations.AlterField(
            model_name='filtroestacoes',
            name='valor_pesquisa',
            field=models.CharField(max_length=500),
        ),
    ]
