# Generated by Django 3.2.5 on 2021-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20210630_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestacoes',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
