# Generated by Django 3.2.4 on 2021-07-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credenciais',
            name='senha',
        ),
    ]
