# Generated by Django 3.2.4 on 2021-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSH_Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('userpass', 'Username and Password'), ('pemkey', 'SSH Key .pem')], max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('sshkey', models.TextField()),
            ],
        ),
    ]
